// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhKgaEa-H9TqL8-B36CseQ2Ur6G1paEwc',
    appId: '1:479525861138:web:f59313399f9f8de6ef25cb',
    messagingSenderId: '479525861138',
    projectId: 'byme-customer',
    authDomain: 'byme-customer.firebaseapp.com',
    storageBucket: 'byme-customer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc4wDgtwQP5c4GNFqHTdKDU1O7uXjlhBU',
    appId: '1:479525861138:android:6dd6d526fb0bc11cef25cb',
    messagingSenderId: '479525861138',
    projectId: 'byme-customer',
    storageBucket: 'byme-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYM80iO7U_OTgYQ_YMD_zuItjY3i_sSnQ',
    appId: '1:479525861138:ios:42aabaa167a3beaaef25cb',
    messagingSenderId: '479525861138',
    projectId: 'byme-customer',
    storageBucket: 'byme-customer.appspot.com',
    iosClientId: '479525861138-q8eol0blie166fbp66ffpb4oi2uvus6d.apps.googleusercontent.com',
    iosBundleId: 'com.byme.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYM80iO7U_OTgYQ_YMD_zuItjY3i_sSnQ',
    appId: '1:479525861138:ios:1588e166c4f7787cef25cb',
    messagingSenderId: '479525861138',
    projectId: 'byme-customer',
    storageBucket: 'byme-customer.appspot.com',
    iosClientId: '479525861138-gh0seriaofbcusia8cikk533j43dpcsa.apps.googleusercontent.com',
    iosBundleId: 'com.byme.app.bymeApp',
  );
}
